
#class RoomService:

    # --------------------
    # ROOM MANAGEMENT
    # --------------------
    #def find_room(): ...
    #def create_room(): ...
    #def join_room(): ...

    # --------------------
    # GAME ENGINE (внутри)
    # --------------------
    #def start_game(): ...
    #def update_state(): ...
    #def finish_game(): ...